export const CATEGORIES = [
  { id: "produce", label: "produce", icon: "🥦" },
  { id: "dairy", label: "dairy", icon: "🥛" },
  { id: "bakery", label: "bakery", icon: "🍞" },
  { id: "meat", label: "meat", icon: "🥩" },
  { id: "beverages", label: "beverages", icon: "🧃" },
  { id: "pantry", label: "pantry", icon: "🫙" },
  { id: "household", label: "household", icon: "🏠" },
  { id: "other", label: "other", icon: "🛒" },
];

const KEYWORDS = {
  produce: [
    "apple",
    "banana",
    "berr",
    "spinach",
    "tomato",
    "avocado",
    "lettuce",
    "onion",
    "potato",
    "carrot",
    "grape",
    "orange",
    "lemon",
    "lime",
    "cucumber",
    "pepper",
    "broccoli",
    "kale",
    "mango",
    "peach",
    "pear",
    "celery",
    "garlic",
    "ginger",
    "herb",
    "salad",
    "fruit",
    "vegetable",
  ],
  dairy: [
    "milk",
    "egg",
    "butter",
    "yogurt",
    "yoghurt",
    "cheese",
    "cream",
    "ghee",
    "curd",
    "paneer",
  ],
  bakery: [
    "bread",
    "bagel",
    "bun",
    "baguette",
    "croissant",
    "pastry",
    "cake",
    "muffin",
    "cookie",
    "biscuit",
    "toast",
  ],
  meat: [
    "chicken",
    "beef",
    "pork",
    "steak",
    "lamb",
    "turkey",
    "bacon",
    "sausage",
    "ham",
    "fish",
    "salmon",
    "shrimp",
    "meat",
    "mince",
  ],
  pantry: [
    "rice",
    "pasta",
    "oil",
    "oat",
    "flour",
    "sugar",
    "salt",
    "spice",
    "sauce",
    "cereal",
    "bean",
    "lentil",
    "dal",
    "atta",
    "honey",
    "vinegar",
    "noodle",
    "chip",
    "ketchup",
  ],
  beverages: ["water", "juice", "soda", "cola", "coffee", "tea"],
  household: [
    "paper",
    "soap",
    "trash",
    "laundry",
    "detergent",
    "tissue",
    "toilet",
    "cleaner",
    "sponge",
    "foil",
    "wrap",
    "bag",
  ],
};

export function categoryOf(name) {
  const text = String(name ?? "").toLowerCase();
  for (const [id, words] of Object.entries(KEYWORDS)) {
    if (words.some((word) => new RegExp(`\\b${word}\\w*`).test(text))) return id;
  }
  return "other";
}

export function categoryMeta(id) {
  return CATEGORIES.find((entry) => entry.id === id) || CATEGORIES.at(-1);
}
